# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rio"
  s.version = "0.0.0"
  s.summary = "Javascript RIA framework for building real-time collaborative web applications on top of Rails."
  s.description = <<-EOF
    Rio is a javascript RIA framework for building real-time collaborative web applications on top of Rails.
    It includes sophisticated binding libraries, client->server and server->client synchronization, transitive 
    dependency management, testing frameworks, and compression and deployment optimization.    
  EOF
  
  s.add_dependency('packr')
  
  s.files = Dir[
     "LICENSE",
     "README.rdoc",
     "lib/**/*"
  ]
  s.require_paths = ["lib"]

  s.rdoc_options = ["--charset=UTF-8"]
  s.has_rdoc = false

  s.authors = ["Jason Tillery", "Vishu Ramanathan"]
  s.email = "tilleryj@gmail.com"
  s.homepage = "http://github.com/tilleryj/rio"
end

